# Generated by Django 3.1.2 on 2020-12-20 11:39

from django.db import migrations, models
import django.db.models.deletion
import subscription.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('name', models.CharField(help_text='Subscription name', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('recurrence', models.DurationField(blank=True, null=True)),
                ('subscription_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_object_fields', models.TextField(blank=True, help_text='key-value pair with the values of the current instance of the related model')),
                ('callback', models.CharField(blank=True, help_text='Dotted path to callable object', max_length=256, null=True, validators=[subscription.validators.ImportCallBackValidator()])),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subscription_event', models.ForeignKey(help_text='Subscription event that determines when the callback canbe called', on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionevent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
