# Generated by Django 3.1.2 on 2020-11-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('name', models.CharField(help_text='Subscription name', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start date')),
                ('end', models.DateTimeField(verbose_name='End date')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start date')),
                ('end', models.DateTimeField(verbose_name='End date')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('recurrence', models.DurationField(blank=True, null=True)),
                ('subscription_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_object_fields', models.TextField(blank=True, help_text='Warning: this field may contain sensitive informationfrom other models')),
                ('callback', models.CharField(blank=True, help_text='Dotted path to callable object', max_length=256, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subscription_event', models.ForeignKey(help_text='the subscription plan for these cost details', on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['content_type', 'object_pk'], name='subscriptio_content_c01529_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['content_type', 'object_pk'], name='subscriptio_content_fc5f02_idx'),
        ),
    ]
