# Generated by Django 3.1.2 on 2021-01-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptionline',
            name='description',
        ),
        migrations.AlterField(
            model_name='resource',
            name='subscription_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionevent'),
        ),
    ]
