# Generated by Django 3.1.2 on 2021-01-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_merge_20210130_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionevent',
            unique_together={('start', 'end', 'subscription_line')},
        ),
    ]
